### ISSUE TITLE
Не могу переоценить фильм на вкладке Rated

### ISSUE THREAD

**Issue by didolf** [isakovairat/moviesApp#1]
При этом на вкладке Search - могу

**Comment by isakovairat** [comment]
Я долго бился как сделать обратную совместимость, вообщем это должен бэк возращать обновленный список с оценками. На фронте это сделать у меня не получается.

**Comment by didolf** [comment]
У тебя должен быть глобальный стор(в app, например) оцененных фильмов.
При переоценке на странице с фильмами ты просто кладешь в него фильм, ну а дальше ты понял(или нет)?

**Comment by isakovairat** [comment]
крч, еле еле родил функцию для апдейта. updateScores криво и понять сложно, но работает
